<html>
    <!--Section: Live preview-->
    <section>

    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalCoupon">Launch
    modal</button>

    <div class="modal-dialog modal-frame modal-top modal-notify modal-success" role="document"
    style="max-width: 100%;">
    <!--Content-->
    <div class="modal-content">
        <!--Body-->
        <div class="modal-body">
        <div class="row d-flex justify-content-center align-items-center">

            <h2>
            <span class="badge">v52gs1</span>
            </h2>
            <p class="pt-3 mx-4">We have a gift for you! Use this code to get a
            <strong>10% discount</strong>.</p>

            <a type="button" class="btn btn-success">Get it
            <i class="fas fa-book ml-1 white-text"></i>
            </a>
            <a type="button" class="btn btn-outline-success waves-effect" data-dismiss="modal">No, thanks</a>
        </div>
        </div>
    </div>
    <!--/.Content-->
    </div>


    </section>
    <!--Section: Live preview-->
</html>